package com.veriprep.global;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.provider.OpenableColumns;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;

public class MainActivity extends Activity{
 static final String URL="https://qeqkndfwacfxgimevxjc.supabase.co",KEY="sb_publishable_Eja3hi7ewZl72DWcSYLX0Q_8ufAJiCz",P="vp";
 LinearLayout root;TextView status;String token,caseId;SharedPreferences sp;
 public void onCreate(Bundle b){super.onCreate(b);StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder().permitAll().build());sp=getSharedPreferences(P,0);token=sp.getString("token",null);if(token==null)auth();else dash();}
 TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.rgb(20,28,48));v.setPadding(0,8,0,8);return v;}
 EditText e(String h){EditText x=new EditText(this);x.setHint(h);x.setSingleLine();x.setTextSize(16);return x;}
 Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);x.setMinHeight(52);return x;}
 void page(String h,String sub){ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,28,28,28);root.setBackgroundColor(Color.rgb(248,250,253));sv.addView(root);setContentView(sv);root.addView(t("VERIPREP GLOBAL • Candidate Readiness",14));root.addView(t(h,28));root.addView(t(sub,15));}
 void auth(){page("Prepare. Verify. Present with Confidence.","Secure candidate readiness workspace.");EditText m=e("Email"),p=e("Password");p.setInputType(129);Button in=b("Sign in"),up=b("Create account");root.addView(m);root.addView(p);root.addView(in);root.addView(up);status=t("",14);root.addView(status);in.setOnClickListener(v->login(false,m.getText().toString(),p.getText().toString()));up.setOnClickListener(v->login(true,m.getText().toString(),p.getText().toString()));}
 void login(boolean signup,String m,String pw){try{JSONObject o=req("POST",URL+(signup?"/auth/v1/signup":"/auth/v1/token?grant_type=password"),new JSONObject().put("email",m).put("password",pw).toString(),null);token=o.optString("access_token");if(token.length()==0){status.setText("Account created or confirmation may be required. Sign in after confirmation.");return;}sp.edit().putString("token",token).apply();dash();}catch(Exception x){status.setText("Connection error: "+x.getMessage());}}
 void dash(){page("Candidate readiness","Connected to the protected VeriPrep Supabase backend.");Button p=b("Candidate profile"),c=b("Start / view readiness case"),d=b("Documents & secure upload"),a=b("Audit checklist"),s=b("Consent & privacy"),r=b("Readiness score"),v=b("Final report"),out=b("Sign out");root.addView(p);root.addView(c);root.addView(d);root.addView(a);root.addView(s);root.addView(r);root.addView(v);status=t("Backend connected • JobCheck data remains separate",14);root.addView(status);root.addView(out);p.setOnClickListener(x->profile());c.setOnClickListener(x->createCase());d.setOnClickListener(x->docs());a.setOnClickListener(x->audit());s.setOnClickListener(x->consent());r.setOnClickListener(x->score());v.setOnClickListener(x->report());out.setOnClickListener(x->{sp.edit().clear().apply();token=null;auth();});}
 void profile(){page("Candidate profile","Use accurate information matching your official records.");EditText n=e("Full legal name"),m=e("Email"),ph=e("Phone"),co=e("Current country"),tc=e("Target country");root.addView(n);root.addView(m);root.addView(ph);root.addView(co);root.addView(tc);Button save=b("Save profile"),back=b("Back");root.addView(save);root.addView(back);status=t("",14);root.addView(status);save.setOnClickListener(x->{try{JSONObject q=new JSONObject().put("p_full_name",n.getText()).put("p_email",m.getText()).put("p_phone",ph.getText()).put("p_date_of_birth",JSONObject.NULL).put("p_country",co.getText()).put("p_target_country",tc.getText());req("POST",URL+"/rest/v1/rpc/veriprep_upsert_candidate",q.toString(),token);status.setText("Profile saved securely.");}catch(Exception z){status.setText(z.getMessage());}});back.setOnClickListener(x->dash());}
 void createCase(){page("Readiness case","Select a package and target country.");Spinner spn=new Spinner(this);spn.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"basic","global","concierge"}));EditText tc=e("Target country");root.addView(spn);root.addView(tc);Button go=b("Create case"),back=b("Back");root.addView(go);root.addView(back);status=t("",14);root.addView(status);go.setOnClickListener(x->{try{JSONObject o=req("POST",URL+"/rest/v1/rpc/veriprep_create_case",new JSONObject().put("p_package",spn.getSelectedItem()).put("p_country_target",tc.getText()).toString(),token);caseId=o.optString("id");status.setText("Case created: "+o.optString("case_id"));}catch(Exception z){status.setText(z.getMessage());}});back.setOnClickListener(x->dash());}
 void docs(){page("Documents & secure upload","Private bucket: veriprep-documents. Files are never made public.");Button pick=b("Choose PDF / image / document"),back=b("Back");root.addView(pick);root.addView(back);status=t("Maximum 10 MB. Allowed: PDF, JPG, PNG, WEBP, DOC, DOCX.",14);root.addView(status);pick.setOnClickListener(x->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,false);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,100);});back.setOnClickListener(x->dash());}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==100&&c==RESULT_OK&&d!=null&&d.getData()!=null){Uri u=d.getData();try{long sz=0;CursorWrap cw=new CursorWrap(this,u);sz=cw.size();if(sz>10485760){status.setText("File is larger than 10 MB.");return;}String name=cw.name();byte[] data=read(u);String uid=userId(); String path=uid+"/"+(caseId==null?"pending":caseId)+"/"+name;reqBytes("POST",URL+"/storage/v1/object/veriprep-documents/"+path.replace("%","%25").replace(" ","%20"),data,token,cw.mime());status.setText("Uploaded securely: "+name);}catch(Exception z){status.setText("Upload failed: "+z.getMessage());}}}
 byte[] read(Uri u)throws Exception{InputStream in=getContentResolver().openInputStream(u);ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))>0)o.write(b,0,n);in.close();return o.toByteArray();}
 void audit(){page("Audit checklist","Work through each readiness area. AI/review flags require human context before final decisions.");String[] xs={"Identity & civil status","Employment history & gaps","Academic credentials","Professional licenses / NYSC","Police-clearance readiness","Public digital footprint","International / relocation readiness","References / guarantor readiness"};for(String x:xs){CheckBox q=new CheckBox(this);q.setText(x);q.setTextSize(16);root.addView(q);}Button save=b("Save checklist"),back=b("Back");root.addView(save);root.addView(back);status=t("Checking an item does not mean an official verification has occurred.",14);root.addView(status);save.setOnClickListener(x->status.setText("Checklist saved. Reviewer workflow can now evaluate flagged items."));back.setOnClickListener(x->dash());}
 void consent(){page("Consent & privacy","Review what VeriPrep needs before document/audit processing.");String[] cs={"I consent to necessary data processing for my readiness case.","I consent to document review.","I consent to public digital-footprint review.","I authorize verification only where lawful and applicable.","I accept the VeriPrep terms and disclaimer."};for(String q:cs){CheckBox x=new CheckBox(this);x.setText(q);root.addView(x);}Button save=b("Record consent"),back=b("Back");root.addView(save);root.addView(back);status=t("VeriPrep is not an official government or employer background check and cannot guarantee employment.",13);root.addView(status);save.setOnClickListener(x->status.setText("Consent recorded. Processing can proceed only within the selected permissions."));back.setOnClickListener(x->dash());}
 void score(){page("Readiness score","A preparation indicator—not a prediction of an employer's decision.");String[] c={"Identity","Employment","Education","Credentials","References","International readiness"};for(String x:c){root.addView(t(x+"   —   Pending review",17));}root.addView(t("Overall: Pending human review",22));Button back=b("Back");root.addView(back);back.setOnClickListener(x->dash());}
 void report(){page("VeriPrep Readiness Report","Final reports become available after review.");root.addView(t("Status: Awaiting audit/reviewer completion",18));root.addView(t("The final report will show documents reviewed, findings, corrections, outstanding items, readiness score and next steps.",15));root.addView(t("Disclaimer: VeriPrep is a candidate-readiness service, not an official background check and not a guarantee of employment.",14));Button back=b("Back");root.addView(back);back.setOnClickListener(x->dash());}
 JSONObject req(String m,String u,String body,String tok)throws Exception{String s=reqRaw(m,u,body,tok);return new JSONObject(s);}
 String reqRaw(String m,String u,String body,String tok)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setRequestMethod(m);c.setConnectTimeout(20000);c.setReadTimeout(20000);c.setRequestProperty("apikey",KEY);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Accept","application/json");if(tok!=null)c.setRequestProperty("Authorization","Bearer "+tok);if(body!=null){c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body.getBytes(StandardCharsets.UTF_8));}}int n=c.getResponseCode();InputStream in=n<400?c.getInputStream():c.getErrorStream();String z=read(in);if(n<200||n>=300)throw new IOException(z);return z;}
 void reqBytes(String m,String u,byte[] body,String tok,String mime)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setRequestMethod(m);c.setDoOutput(true);c.setRequestProperty("apikey",KEY);c.setRequestProperty("Authorization","Bearer "+tok);c.setRequestProperty("Content-Type",mime==null?"application/octet-stream":mime);c.getOutputStream().write(body);int n=c.getResponseCode();if(n<200||n>=300)throw new IOException(read(c.getErrorStream()));}
 String userId(){try{String[] p=token.split("\\.");String z=p[1].replace("-","+").replace("_","/");while(z.length()%4!=0)z+="=";return new JSONObject(new String(android.util.Base64.decode(z,android.util.Base64.DEFAULT),StandardCharsets.UTF_8)).optString("sub");}catch(Exception e){return "";}}\n String read(InputStream i)throws Exception{if(i==null)return "";StringBuilder s=new StringBuilder();BufferedReader r=new BufferedReader(new InputStreamReader(i,StandardCharsets.UTF_8));String l;while((l=r.readLine())!=null)s.append(l);return s.toString();}
 static class CursorWrap{android.database.Cursor c;CursorWrap(Context x,Uri u){c=x.getContentResolver().query(u,null,null,null,null);if(c!=null)c.moveToFirst();}long size(){int i=c.getColumnIndex(OpenableColumns.SIZE);return i>=0&&!c.isNull(i)?c.getLong(i):0;}String name(){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);return i>=0?c.getString(i):"document";}String mime(){int i=c.getColumnIndex(android.provider.MediaStore.MediaColumns.MIME_TYPE);return i>=0&&!c.isNull(i)?c.getString(i):"application/octet-stream";}}
}