import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import { ShieldCheck, Search, Upload, FileWarning, Lock, ArrowRight, CheckCircle2, ClipboardList, Flag, X, LogIn, ChevronRight, LogOut, LayoutDashboard, Users, Image as ImageIcon, RefreshCw, Check, Ban, Clock3 } from 'lucide-react';
import './styles.css';

const SUPABASE_URL = 'https://qeqkndfwacfxgimevxjc.supabase.co';
const SUPABASE_KEY = 'sb_publishable_Eja3hi7ewZl72DWcSYLX0Q_8ufAJiCz';
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

const checks = ['Requests for upfront registration, training, equipment or processing fees','Promises of unusually high pay for very little work','Pressure to move conversations or payments off-platform','Suspicious links, fake company identities or inconsistent contact details'];
const demoHistory = [
  { title: 'Remote Data Entry Offer', level: 'High Risk', date: 'Today', reason: 'Upfront payment request' },
  { title: 'Freelance Design Contract', level: 'Needs Review', date: 'Yesterday', reason: 'Off-platform communication' },
  { title: 'Customer Support Role', level: 'Low Risk', date: 'Sep 9', reason: 'No major red flags detected' }
];

function App(){
 const [page,setPage]=useState('home'),[jobText,setJobText]=useState(''),[result,setResult]=useState(null),[showLogin,setShowLogin]=useState(false),[authMode,setAuthMode]=useState('signin'),[user,setUser]=useState(null),[profile,setProfile]=useState(null),[authBusy,setAuthBusy]=useState(false),[authMessage,setAuthMessage]=useState(''),[reportSent,setReportSent]=useState(false),[history,setHistory]=useState([]),[reportForm,setReportForm]=useState({title:'',company:'',source:'WhatsApp',amount:'',description:'',evidence:null}),[adminReports,setAdminReports]=useState([]),[adminStats,setAdminStats]=useState({users:0,checks:0,pending:0,highRisk:0}),[adminBusy,setAdminBusy]=useState(false),[moderationNote,setModerationNote]=useState({});
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user||null));const {data:listener}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>listener.subscription.unsubscribe()},[]);
 useEffect(()=>{if(user){loadProfile();loadHistory()}else setProfile(null)},[user]);
 useEffect(()=>{if(profile&&(profile.role==='admin'||profile.role==='moderator'))loadAdmin()},[profile]);
 async function loadProfile(){const {data}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();setProfile(data||null)}
 async function loadHistory(){const {data}=await supabase.from('job_checks').select('*').order('created_at',{ascending:false}).limit(30);setHistory(data||[])}
 async function analyze(){if(!jobText.trim())return;const text=jobText.toLowerCase();const flags=checks.filter((_,i)=>i===0?/pay|fee|charge|registration|training|deposit|money|payment/.test(text):i===1?/easy money|huge salary|1000\$|\$1000|₦|million/.test(text):i===2?/telegram|whatsapp|crypto|gift card|send.*money/.test(text):/http|click|verify|urgent|gmail|outlook/.test(text));const level=flags.length>=2?'High Risk':flags.length===1?'Needs Review':'Low Risk';const riskScore=level==='High Risk'?Math.min(95,60+flags.length*12):level==='Needs Review'?45:15;setResult({level,flags,riskScore});if(user){await supabase.from('job_checks').insert({user_id:user.id,title:jobText.trim().slice(0,70),job_text:jobText.trim(),risk_level:level==='High Risk'?'high':level==='Needs Review'?'medium':'low',risk_score:riskScore,red_flags:flags,recommendations:['Verify the employer independently.','Do not send money to get a job.','Avoid sharing sensitive documents until the employer is verified.']});loadHistory()}}
 async function submitAuth(e){e.preventDefault();setAuthBusy(true);setAuthMessage('');const f=new FormData(e.currentTarget),email=String(f.get('email')||'').trim(),password=String(f.get('password')||''),fullName=String(f.get('fullName')||'').trim();const r=authMode==='signup'?await supabase.auth.signUp({email,password,options:{data:{full_name:fullName}}}):await supabase.auth.signInWithPassword({email,password});setAuthBusy(false);if(r.error)return setAuthMessage(r.error.message);if(authMode==='signup'&&!r.data.session)return setAuthMessage('Account created. Check your email if confirmation is required, then sign in.');setShowLogin(false);setPage('dashboard')}
 async function signOut(){await supabase.auth.signOut();setUser(null);setPage('home')}
 async function uploadEvidence(file,reportId){if(!file||!user)return null;if(!file.type.startsWith('image/'))throw new Error('Only image evidence is supported.');if(file.size>8*1024*1024)throw new Error('Evidence image must be 8MB or smaller.');const path=`${user.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error:up}=await supabase.storage.from('job-evidence').upload(path,file,{contentType:file.type,upsert:false});if(up)throw up;const {data,error}=await supabase.from('job_evidence').insert({user_id:user.id,report_id:reportId,storage_path:path,file_name:file.name,mime_type:file.type,file_size:file.size}).select().single();if(error)throw error;return data}
 async function submitReport(e){e.preventDefault();if(!user){setShowLogin(true);setAuthMode('signin');return}const {data,error}=await supabase.from('reports').insert({user_id:user.id,title:reportForm.title,description:`${reportForm.company?`Company/recruiter: ${reportForm.company}\n`:''}${reportForm.amount?`Amount requested: ${reportForm.amount}\n`:''}${reportForm.description}`,source:reportForm.source}).select().single();if(error)return setAuthMessage(error.message);try{if(reportForm.evidence)await uploadEvidence(reportForm.evidence,data.id)}catch(err){setAuthMessage(`Report saved, but evidence upload failed: ${err.message}`)}setReportSent(true)}
 async function loadAdmin(){setAdminBusy(true);const [{data:reports},{count:users},{count:checksCount},{count:pending},{count:highRisk}]=await Promise.all([supabase.from('reports').select('*, profiles:user_id(email,full_name)').order('created_at',{ascending:false}).limit(100),supabase.from('profiles').select('*',{count:'exact',head:true}),supabase.from('job_checks').select('*',{count:'exact',head:true}),supabase.from('reports').select('*',{count:'exact',head:true}).eq('moderation_status','pending'),supabase.from('job_checks').select('*',{count:'exact',head:true}).eq('risk_level','high')]);setAdminReports(reports||[]);setAdminStats({users:users||0,checks:checksCount||0,pending:pending||0,highRisk:highRisk||0});setAdminBusy(false)}
 async function moderateReport(id,status){const {error}=await supabase.from('reports').update({moderation_status:status,moderator_id:user.id,moderator_note:moderationNote[id]||null,reviewed_at:new Date().toISOString()}).eq('id',id);if(!error)loadAdmin()}
 async function viewEvidence(reportId){const {data}=await supabase.from('job_evidence').select('*').eq('report_id',reportId).order('created_at');if(!data?.length)return alert('No evidence attached to this report.');for(const item of data){const {data:s}=await supabase.storage.from('job-evidence').createSignedUrl(item.storage_path,300);if(s?.signedUrl)window.open(s.signedUrl,'_blank','noopener,noreferrer')}}
 const go=n=>{setPage(n);window.scrollTo({top:0,behavior:'smooth'})};const isStaff=profile?.role==='admin'||profile?.role==='moderator';const recent=history.length?history:demoHistory;
 return <div className="app">
 <header className="nav"><button className="brand brandButton" onClick={()=>go('home')}><div className="brandIcon"><ShieldCheck size={23}/></div><span>JobCheck <b>NG</b></span></button><nav><button onClick={()=>go('home')}>Job Checker</button><button onClick={()=>go('dashboard')}>Dashboard</button><button onClick={()=>go('report')}>Report a Job</button>{isStaff&&<button onClick={()=>go('admin')}><LayoutDashboard size={15}/> Admin</button>}{user?<button className="login" onClick={signOut}><LogOut size={15}/> Sign out</button>:<button className="login" onClick={()=>{setAuthMode('signin');setShowLogin(true)}}><LogIn size={15}/> Sign in</button>}</nav></header>
 {page==='home'&&<main><section className="hero"><div className="heroCopy"><div className="pill"><ShieldCheck size={15}/> Built for safer job hunting in Nigeria</div><h1>Check the job.<br/><span>Protect your money.</span></h1><p>Paste a job offer, message, or suspicious request and JobCheck NG will help you identify scam warning signs before you pay or share sensitive information.</p><button className="primary" onClick={()=>document.getElementById('checker')?.scrollIntoView({behavior:'smooth'})}>Check a Job <ArrowRight size={18}/></button></div><div className="heroCard"><div className="scanRing"><ShieldCheck size={48}/></div><strong>Job safety starts here.</strong><span>Free checks • Private by design</span></div></section>
 <section id="checker" className="checker section"><div className="sectionHead"><div><span className="eyebrow">JOB CHECKER</span><h2>Is this job offer safe?</h2><p>Paste the job description, recruiter message, or payment request below.</p></div><div className="secure"><Lock size={15}/> Your text stays private</div></div><div className="checkerGrid"><div className="inputCard"><textarea value={jobText} onChange={e=>setJobText(e.target.value)} placeholder="Paste the job offer here...\n\nExample: You have been selected for a remote job. Pay ₦25,000 for registration before we can start your onboarding."/><div className="inputFooter"><label className="upload"><Upload size={16}/> Upload screenshot <input type="file" accept="image/*" hidden /></label><button onClick={analyze} className="analyze"><Search size={17}/> Analyze offer</button></div></div><div className="resultCard">{!result?<><div className="emptyIcon"><FileWarning size={27}/></div><h3>Your safety result will appear here</h3><p>JobCheck looks for common scam patterns and explains the warning signs it finds.</p></>:<><div className={`risk ${result.level.replaceAll(' ','-').toLowerCase()}`}><CheckCircle2 size={20}/>{result.level} · {result.riskScore}/100</div><h3>{result.flags.length?'Warning signs detected':'No obvious red flags found'}</h3>{result.flags.length?<ul>{result.flags.map((f,i)=><li key={i}>{f}</li>)}</ul>:<p>This is not a guarantee that the offer is legitimate. Verify the employer independently before accepting or paying.</p>}</>}</div></div></section>
 <section className="how section"><span className="eyebrow">HOW IT WORKS</span><h2>Three simple steps to a safer decision.</h2><div className="steps"><div><b>01</b><h3>Paste or upload</h3><p>Bring the offer, chat, email or screenshot you want checked.</p></div><div><b>02</b><h3>Scan for red flags</h3><p>JobCheck checks for common payment, identity and pressure tactics.</p></div><div><b>03</b><h3>Decide with confidence</h3><p>Get clear risk signals and practical next steps before you proceed.</p></div></div></section><section className="report section"><div><span className="eyebrow">HELP OTHERS</span><h2>Found a suspicious job?</h2><p>Report it so other Nigerian job seekers can avoid the same trap.</p></div><button className="secondary" onClick={()=>go('report')}>Report a Job <ArrowRight size={17}/></button></section></main>}
 {page==='dashboard'&&<main className="dashboardPage section"><div className="pageTitle"><div><span className="eyebrow">MY ACCOUNT</span><h1>Dashboard</h1><p>{user?`Signed in as ${user.email}`:'Sign in to save checks and reports to your account.'}</p></div><button className="primary" onClick={()=>go('home')}>New Job Check <Search size={17}/></button></div><div className="statGrid"><div className="stat"><Search/><strong>{history.length}</strong><span>Saved checks</span></div><div className="stat"><Flag/><strong>—</strong><span>Reports submitted</span></div><div className="stat"><CheckCircle2/><strong>{history.filter(x=>x.risk_level==='low').length}</strong><span>Low-risk results</span></div><div className="stat"><ShieldCheck/><strong>{history.filter(x=>x.risk_level==='high').length}</strong><span>High-risk results</span></div></div><div className="dashboardGrid"><section className="panel"><div className="panelHead"><h2>Recent checks</h2><button onClick={()=>go('checks')}>View all <ChevronRight size={16}/></button></div>{recent.slice(0,5).map((item,i)=>{const level=item.level||(item.risk_level==='high'?'High Risk':item.risk_level==='medium'?'Needs Review':'Low Risk');return <div className="history" key={item.id||i}><div className="historyIcon"><ClipboardList size={18}/></div><div className="historyMain"><strong>{item.title}</strong><span>{item.reason||(item.red_flags?.[0]||'No major red flags detected')}</span></div><div className={`miniRisk ${level.replaceAll(' ','-').toLowerCase()}`}>{level}</div><small>{item.created_at?new Date(item.created_at).toLocaleDateString():item.date}</small></div>})}</section><section className="panel safety"><ShieldCheck size={30}/><h2>Safety reminder</h2><p>Never pay an employer to get a job. Verify company details using an independent source before sending money or documents.</p></section></div></main>}
 {page==='checks'&&<main className="dashboardPage section"><div className="pageTitle"><div><span className="eyebrow">HISTORY</span><h1>My Checks</h1></div></div><section className="panel fullPanel">{(user?history:demoHistory).map((item,i)=>{const level=item.level||(item.risk_level==='high'?'High Risk':item.risk_level==='medium'?'Needs Review':'Low Risk');return <div className="history" key={item.id||i}><div className="historyIcon"><ClipboardList size={18}/></div><div className="historyMain"><strong>{item.title}</strong><span>{item.reason||(item.red_flags?.[0]||'No major red flags detected')}</span></div><div className={`miniRisk ${level.replaceAll(' ','-').toLowerCase()}`}>{level}</div><small>{item.created_at?new Date(item.created_at).toLocaleDateString():item.date}</small></div>})}</section></main>}
 {page==='report'&&<main className="dashboardPage section"><div className="pageTitle"><div><span className="eyebrow">COMMUNITY SAFETY</span><h1>Report a Job</h1><p>Share a suspicious job so other people can avoid the same trap.</p></div></div><section className="formPanel">{reportSent?<div className="successBox"><CheckCircle2 size={42}/><h2>Report received</h2><p>Thank you. Your report has been saved for moderation.</p><button className="primary" onClick={()=>{setReportSent(false);setReportForm({title:'',company:'',source:'WhatsApp',amount:'',description:'',evidence:null})}}>Submit another report</button></div>:<form onSubmit={submitReport}><div className="formGrid"><label>Job title<input required value={reportForm.title} onChange={e=>setReportForm({...reportForm,title:e.target.value})} placeholder="e.g. Remote data entry"/></label><label>Company / recruiter<input value={reportForm.company} onChange={e=>setReportForm({...reportForm,company:e.target.value})} placeholder="Name shown in the offer"/></label><label>Where did you find it?<select value={reportForm.source} onChange={e=>setReportForm({...reportForm,source:e.target.value})}><option>WhatsApp</option><option>Telegram</option><option>Facebook</option><option>Upwork / Fiverr</option><option>Email</option><option>Other</option></select></label><label>Amount requested<input value={reportForm.amount} onChange={e=>setReportForm({...reportForm,amount:e.target.value})} placeholder="e.g. ₦25,000"/></label></div><label>What happened?<textarea required value={reportForm.description} onChange={e=>setReportForm({...reportForm,description:e.target.value})} placeholder="Explain the suspicious request, payment demand, links, or messages..."/></label><label className="uploadBox"><Upload size={19}/> {reportForm.evidence?reportForm.evidence.name:'Attach screenshot / evidence (optional)'}<input type="file" accept="image/*" hidden onChange={e=>setReportForm({...reportForm,evidence:e.target.files?.[0]||null})}/></label><button className="primary" type="submit">{user?'Submit report':'Sign in to submit'} <ArrowRight size={17}/></button></form>}</section></main>}
 {page==='admin'&&isStaff&&<main className="dashboardPage section adminPage"><div className="pageTitle"><div><span className="eyebrow">PRIVATE STAFF AREA</span><h1>Admin Dashboard</h1><p>Monitor users, checks, evidence and community reports.</p></div><button className="secondary" onClick={loadAdmin}><RefreshCw size={16}/> Refresh</button></div><div className="statGrid"><div className="stat"><Users/><strong>{adminStats.users}</strong><span>Users</span></div><div className="stat"><Search/><strong>{adminStats.checks}</strong><span>Total checks</span></div><div className="stat"><Clock3/><strong>{adminStats.pending}</strong><span>Pending reports</span></div><div className="stat"><ShieldCheck/><strong>{adminStats.highRisk}</strong><span>High-risk checks</span></div></div><div className="adminGrid"><section className="panel"><div className="panelHead"><h2>Report moderation</h2><span>{adminReports.filter(r=>r.moderation_status==='pending'||r.moderation_status==='reviewing').length} awaiting action</span></div>{adminBusy?<p>Loading moderation queue…</p>:adminReports.length===0?<p>No reports have been submitted yet.</p>:adminReports.map(r=><article className="moderationCard" key={r.id}><div className="moderationTop"><div><strong>{r.title||'Untitled report'}</strong><span>{r.profiles?.email||'Unknown user'} · {new Date(r.created_at).toLocaleString()}</span></div><span className={`statusBadge ${r.moderation_status}`}>{r.moderation_status}</span></div><p>{r.description}</p><div className="moderationActions"><button className="secondary" onClick={()=>viewEvidence(r.id)}><ImageIcon size={16}/> View evidence</button><button className="secondary" onClick={()=>moderateReport(r.id,'reviewing')}>Reviewing</button><button className="approve" onClick={()=>moderateReport(r.id,'approved')}><Check size={16}/> Approve</button><button className="reject" onClick={()=>moderateReport(r.id,'rejected')}><Ban size={16}/> Reject</button><button className="secondary" onClick={()=>moderateReport(r.id,'resolved')}>Resolve</button></div><textarea className="moderatorNote" value={moderationNote[r.id]||''} onChange={e=>setModerationNote({...moderationNote,[r.id]:e.target.value})} placeholder="Private moderator note (optional)…"/></article>)}</section><section className="panel"><div className="panelHead"><h2>Staff tools</h2></div><div className="adminTool"><ShieldCheck/><div><strong>Protected staff access</strong><p>Only admin or moderator profiles can see this dashboard.</p></div></div><div className="adminTool"><ImageIcon/><div><strong>Private evidence vault</strong><p>Evidence is stored in a non-public bucket and opened through short-lived signed URLs.</p></div></div><div className="adminTool"><Flag/><div><strong>Moderation workflow</strong><p>Pending → Reviewing → Approved / Rejected → Resolved.</p></div></div></section></div></main>}
 <footer><span>© 2026 JobCheck NG</span><span>Safer job hunting starts with a check.</span></footer>
 {showLogin&&<div className="modalBackdrop" onClick={()=>setShowLogin(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowLogin(false)}><X/></button><div className="modalIcon"><LogIn/></div><h2>{authMode==='signup'?'Create your JobCheck NG account':'Sign in to JobCheck NG'}</h2><p>Secure email and password authentication powered by Supabase.</p><form onSubmit={submitAuth}>{authMode==='signup'&&<label>Full name<input name="fullName" required placeholder="Your name"/></label>}<label>Email<input name="email" type="email" required placeholder="you@example.com"/></label><label>Password<input name="password" type="password" required minLength="6" placeholder="••••••••"/></label>{authMessage&&<div className="authMessage">{authMessage}</div>}<button className="primary" disabled={authBusy}>{authBusy?'Please wait…':authMode==='signup'?'Create account':'Sign in'} <ArrowRight size={17}/></button></form><button className="textButton" onClick={()=>{setAuthMode(authMode==='signup'?'signin':'signup');setAuthMessage('')}}>{authMode==='signup'?'Already have an account? Sign in':'Need an account? Create one'}</button></div></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
