const KEY='jobcheckng_safety_reports_v1';
const getReports=()=>JSON.parse(localStorage.getItem(KEY)||'[]');
const saveReports=(r)=>localStorage.setItem(KEY,JSON.stringify(r));

function scoreText(text){
 const t=text.toLowerCase();
 const rules=[
  [/\b(pay|payment|fee|registration|training fee|deposit|processing fee|equipment fee|unlock)\b/,25,'Upfront payment request'],
  [/\b(whatsapp|telegram|crypto|gift card|send money)\b/,15,'High-risk payment/contact channel'],
  [/\b(urgent|immediately|today only|act now|limited slot)\b/,10,'Pressure or urgency'],
  [/\b(guaranteed|easy money|no experience|\$[0-9,]+|₦[0-9,]+,?000,?000)\b/,12,'Unusually attractive promise'],
  [/(gmail|outlook|yahoo)\.(com|net)/,10,'Free email domain used for recruitment'],
  [/(click|verify|login|bit\.ly|tinyurl|t\.co)/,8,'Suspicious link or credential request'],
  [/(passport|bvn|nin|otp|bank details|card number|pin)/,15,'Sensitive information request']
 ];
 let score=5, flags=[]; for(const [re,pts,label] of rules){if(re.test(t)){score+=pts;flags.push(label)}}
 score=Math.min(100,score); return {score,flags,level:score>=65?'HIGH RISK':score>=35?'NEEDS REVIEW':'LOW RISK'};
}

function mount(){
 if(document.getElementById('jc-safety-center')) return;
 const style=document.createElement('style'); style.textContent=`
 #jc-safety-center{font-family:Inter,system-ui,sans-serif;position:fixed;right:16px;bottom:16px;z-index:99999;color:#101828}
 #jc-safety-center .jc-fab{border:0;border-radius:999px;padding:13px 17px;background:#111827;color:#fff;font-weight:800;box-shadow:0 10px 30px #0003;cursor:pointer}
 #jc-safety-center .jc-panel{display:none;width:min(390px,calc(100vw - 28px));max-height:78vh;overflow:auto;background:#fff;border:1px solid #e4e7ec;border-radius:20px;box-shadow:0 24px 70px #0004;padding:18px;margin-bottom:10px}
 #jc-safety-center.open .jc-panel{display:block}.jc-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}.jc-title b{font-size:18px}.jc-close{border:0;background:#f2f4f7;border-radius:10px;padding:7px;cursor:pointer}.jc-sub{color:#667085;font-size:13px;margin-bottom:14px}.jc-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.jc-card{border:1px solid #eaecf0;border-radius:14px;padding:12px;background:#fcfcfd;cursor:pointer}.jc-card b{display:block;font-size:13px}.jc-card span{font-size:11px;color:#667085}.jc-view{display:none;margin-top:12px}.jc-view.active{display:block}.jc-view textarea,.jc-view input,.jc-view select{width:100%;box-sizing:border-box;border:1px solid #d0d5dd;border-radius:10px;padding:10px;margin:5px 0 8px;font:inherit}.jc-btn{border:0;border-radius:10px;padding:10px 13px;background:#111827;color:#fff;font-weight:700;cursor:pointer}.jc-result{margin-top:10px;padding:12px;border-radius:12px;background:#f2f4f7}.jc-high{background:#fff0f0;color:#b42318}.jc-med{background:#fff8e8;color:#b54708}.jc-low{background:#ecfdf3;color:#027a48}.jc-small{font-size:12px;color:#667085}.jc-list{padding-left:18px;font-size:13px}.jc-report{border-top:1px solid #eaecf0;margin-top:10px;padding-top:10px}.jc-link{color:#175cd3;font-weight:700;cursor:pointer}`; document.head.appendChild(style);
 const root=document.createElement('div'); root.id='jc-safety-center'; root.innerHTML=`<button class="jc-fab">🛡️ Safety Center</button><div class="jc-panel"><div class="jc-title"><b>JobCheck NG Safety Center</b><button class="jc-close">✕</button></div><div class="jc-sub">Advanced tools to help Nigerian job seekers check before they pay or share sensitive information.</div><div class="jc-grid"><div class="jc-card" data-v="scan"><b>🤖 AI Scam Score</b><span>0–100 risk analysis</span></div><div class="jc-card" data-v="pay"><b>💰 Before You Pay</b><span>Payment-risk check</span></div><div class="jc-card" data-v="company"><b>🏢 Company Check</b><span>Review employer signals</span></div><div class="jc-card" data-v="link"><b>🔗 Job Link Scanner</b><span>Inspect suspicious links</span></div><div class="jc-card" data-v="report"><b>🚨 Community Reports</b><span>Save a scam report</span></div><div class="jc-card" data-v="premium"><b>⭐ Premium</b><span>Advanced protection</span></div></div>
 <div id="jc-scan" class="jc-view"><textarea id="jc-text" rows="5" placeholder="Paste a job offer, WhatsApp message, email or recruiter message..."></textarea><button class="jc-btn" id="jc-analyze">Analyze Risk</button><div id="jc-result"></div></div>
 <div id="jc-pay" class="jc-view"><input id="jc-amount" placeholder="Amount requested, e.g. ₦25,000"/><textarea id="jc-paytext" rows="4" placeholder="Why are they asking you to pay?"></textarea><button class="jc-btn" id="jc-paycheck">Check Before You Pay</button><div id="jc-payresult"></div></div>
 <div id="jc-company" class="jc-view"><input id="jc-companyname" placeholder="Company / recruiter name"/><input id="jc-domain" placeholder="Website or email domain (optional)"/><button class="jc-btn" id="jc-companycheck">Check Signals</button><div id="jc-companyresult"></div></div>
 <div id="jc-link" class="jc-view"><input id="jc-url" placeholder="Paste job URL"/><button class="jc-btn" id="jc-linkcheck">Scan Link</button><div id="jc-linkresult"></div></div>
 <div id="jc-report" class="jc-view"><input id="jc-rtitle" placeholder="Job title"/><input id="jc-rcompany" placeholder="Company / recruiter"/><textarea id="jc-rdesc" rows="4" placeholder="What happened? Include warning signs, but do not post passwords, OTPs or full bank/card details."></textarea><button class="jc-btn" id="jc-save">Save Community Report</button><div id="jc-reports"></div></div>
 <div id="jc-premium" class="jc-view"><div class="jc-result"><b>JobCheck NG Premium — ₦5,000/month</b><p class="jc-small">Planned premium protection: unlimited checks, advanced screenshot analysis, detailed reports, evidence vault, scam alerts and priority analysis.</p><p class="jc-small">Payment remains through the existing Paystack integration.</p></div></div></div>`; document.body.appendChild(root);
 const openView=v=>{root.querySelectorAll('.jc-view').forEach(x=>x.classList.remove('active'));document.getElementById('jc-'+v)?.classList.add('active')};
 root.querySelector('.jc-fab').onclick=()=>root.classList.toggle('open'); root.querySelector('.jc-close').onclick=()=>root.classList.remove('open'); root.querySelectorAll('.jc-card').forEach(c=>c.onclick=()=>{openView(c.dataset.v);if(c.dataset.v==='report')renderReports()});
 document.getElementById('jc-analyze').onclick=()=>{const r=scoreText(document.getElementById('jc-text').value);document.getElementById('jc-result').innerHTML=`<div class="jc-result ${r.level==='HIGH RISK'?'jc-high':r.level==='NEEDS REVIEW'?'jc-med':'jc-low'}"><b>${r.level} — ${r.score}/100</b><ul class="jc-list">${(r.flags.length?r.flags:['No obvious red flags detected']).map(x=>`<li>${x}</li>`).join('')}</ul><span class="jc-small">This is a risk signal, not proof of legitimacy. Verify independently before paying.</span></div>`};
 document.getElementById('jc-paycheck').onclick=()=>{const t=document.getElementById('jc-paytext').value+' '+document.getElementById('jc-amount').value;const r=scoreText(t+' payment fee deposit registration');document.getElementById('jc-payresult').innerHTML=`<div class="jc-result jc-high"><b>⚠️ ${r.level}</b><p class="jc-small">If an unknown employer requires money before you can get a job, stop and independently verify the employer. Never share OTPs, PINs or card details.</p></div>`};
 document.getElementById('jc-companycheck').onclick=()=>{const n=document.getElementById('jc-companyname').value.trim(),d=document.getElementById('jc-domain').value.trim().toLowerCase();const warnings=[];if(!n)warnings.push('Company name is missing.');if(d&&/(gmail|yahoo|outlook|hotmail)\./.test(d))warnings.push('Recruitment contact uses a free email domain.');if(!d)warnings.push('No official website/domain supplied.');document.getElementById('jc-companyresult').innerHTML=`<div class="jc-result ${warnings.length?'jc-med':'jc-low'}"><b>${warnings.length?'Needs independent verification':'No obvious contact-format warning'}</b><ul class="jc-list">${warnings.map(x=>`<li>${x}</li>`).join('')||'<li>Still verify the company through independent public sources.</li>'}</ul></div>`};
 document.getElementById('jc-linkcheck').onclick=()=>{const u=document.getElementById('jc-url').value.trim();let warnings=[];try{const x=new URL(u);if(x.protocol!=='https:')warnings.push('Link is not HTTPS.');if(/bit\.ly|tinyurl|t\.co|\.ru\b|\.tk\b/i.test(x.hostname))warnings.push('Shortened or unusual domain detected.');warnings.push('Do not enter passwords, OTPs or bank details from an unverified job link.')}catch(e){warnings.push('Invalid URL. Paste the full job link.')}document.getElementById('jc-linkresult').innerHTML=`<div class="jc-result ${warnings.length?'jc-med':'jc-low'}"><b>${warnings.length?'Review carefully':'Basic link format looks OK'}</b><ul class="jc-list">${warnings.map(x=>`<li>${x}</li>`).join('')}</ul></div>`};
 document.getElementById('jc-save').onclick=()=>{const r={title:document.getElementById('jc-rtitle').value,company:document.getElementById('jc-rcompany').value,description:document.getElementById('jc-rdesc').value,date:new Date().toLocaleString()};if(!r.title||!r.description)return alert('Add a title and description.');const all=getReports();all.unshift(r);saveReports(all);document.getElementById('jc-rtitle').value='';document.getElementById('jc-rcompany').value='';document.getElementById('jc-rdesc').value='';renderReports()};
 function renderReports(){const a=getReports();document.getElementById('jc-reports').innerHTML=a.length?`<div class="jc-report"><b>${a.length} saved community report(s)</b>${a.slice(0,5).map(r=>`<p class="jc-small"><b>${r.title}</b>${r.company?' — '+r.company:''}<br>${r.description.slice(0,140)}...</p>`).join('')}</div>`:'<p class="jc-small">No reports saved on this device yet.</p>'}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();